export const RESEND_OTP='account/resend_otp/'
export const VERIFY_OTP='account/otp_verify/'
export const BASE_URL= 'http://ec2-3-15-42-254.us-east-2.compute.amazonaws.com:8080/'
export const GET_STATE_AND_DISTRICT_LIST='account/state_district/'
export const SIGN_UP='account/register/'